FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY new_location_orchestrator.py .

CMD [ "new_location_orchestrator.lambda_handler" ]