FROM python:3.13.5

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY homepage.py .

COPY .streamlit ./.streamlit

COPY pages ./pages

COPY modules ./modules

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1

ENTRYPOINT ["streamlit", "run", "homepage.py", "--server.port=8501", "--server.address=0.0.0.0"]