FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY fetch_live_flood_warnings.py .

CMD [ "fetch_live_flood_warnings.lambda_handler" ]