FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY extract_air_quality.py .

CMD [ "extract_air_quality.lambda_handler" ]
