name: Test and Lint
on:
  push:
    branches:
    - 'main'
  pull_request: 
    branches:
    - 'main'
  workflow_dispatch:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pytest
          find . -name "requirements.txt" -exec pip install -r {} \;
      - name: Run tests
        run: find . -name "test*.py" -exec pytest {} \;
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install pylint
          find . -name "requirements.txt" -exec pip install -r {} \;
      - name: Run pylint
        run: |
          find . -name "*.py" -and -not -name "test*" -and -type f -and -not -path "*.venv*" -and -not -path "*.utils*" -exec pylint {} --fail-under 8.5 \;